################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: 3DSecure  
    link: docs/3DSecure.md
- sections:
  - title: Digital Wallets  
    link: docs/DigitalWallets.md
- sections:
  - title: Release notes
    sections:
    - title: March 2022
      link: docs/release-notes/2022/march.md
- sections:
  - title: Resources
    sections:
    - title: SDKs
      link: docs/Sdks.md
- sections:
  - title: Schemas
    sections:
    - title: BasicResponse
      link: docs/schemas-md/BasicResponse.md
    - title: ErrorResponse
      link: docs/schemas-md/ErrorResponse.md  
    - title: TransactionErrorResponse
      link: docs/schemas-md/TransactionErrorResponse.md   
    - title: PaymentUrlErrorResponse
      link: docs/schemas-md/PaymentUrlErrorResponse.md   
    - title: PaymentSchedulesErrorResponse
      link: docs/schemas-md/PaymentSchedulesErrorResponse.md     
    - title: PaymentTokenizationErrorResponse
      link: docs/schemas-md/PaymentTokenizationErrorResponse.md    
    - title: OrderErrorResponse
      link: docs/schemas-md/OrderErrorResponse.md    
    - title: OrderResponse
      link: docs/schemas-md/OrderResponse.md    
    - title: PaymentTokenUpdateResponse
      link: docs/schemas-md/PaymentTokenUpdateResponse.md    
    - title: PaymentTokenizationResponse
      link: docs/schemas-md/PaymentTokenizationResponse.md  
    - title: PaymentSchedulesResponse
      link: docs/schemas-md/PaymentSchedulesResponse.md     
    - title: RecurringPaymentDetailsResponse
      link: docs/schemas-md/RecurringPaymentDetailsResponse.md      
    - title: ExchangeRateResponse
      link: docs/schemas-md/ExchangeRateResponse.md
    - title: PaymentUrlResponse
      link: docs/schemas-md/PaymentUrlResponse.md          
    - title: PaymentUrlDetailResponse
      link: docs/schemas-md/PaymentUrlDetailResponse.md         
    - title: TransactionResponse
      link: docs/schemas-md/TransactionResponse.md
    - title: RecurringPaymentDetails
      link: docs/schemas-md/RecurringPaymentDetails.md 
    - title: PaymentMethodPaymentSchedulesRequest
      link: docs/schemas-md/PaymentMethodPaymentSchedulesRequest.md              
    - title: ReferencedOrderPaymentSchedulesRequest
      link: docs/schemas-md/ReferencedOrderPaymentSchedulesRequest.md            
    - title: Frequency
      link: docs/schemas-md/Frequency.md     
    - title: ClientLocale
      link: docs/schemas-md/ClientLocale.md        
    - title: AccessTokenRequest
      link: docs/schemas-md/AccessTokenRequest.md           
    - title: AccessTokenResponse
      link: docs/schemas-md/AccessTokenResponse.md   
    - title: CardVerificationRequest
      link: docs/schemas-md/CardVerificationRequest.md       
    - title: GenerateCashReceiptRequest
      link: docs/schemas-md/GenerateCashReceiptRequest.md      
    - title: GenerateCashReceiptResponse
      link: docs/schemas-md/GenerateCashReceiptResponse.md        
    - title: DeliveryConfirmationRequest
      link: docs/schemas-md/DeliveryConfirmationRequest.md   
    - title: DeliveryConfirmationResponse
      link: docs/schemas-md/DeliveryConfirmationResponse.md     
    - title: PaymentCardVerificationRequest
      link: docs/schemas-md/PaymentCardVerificationRequest.md     
    - title: PaymentTokenVerificationRequest
      link: docs/schemas-md/PaymentTokenVerificationRequest.md       
    - title: ReferencedOrderPaymentTokenizationRequest
      link: docs/schemas-md/ReferencedOrderPaymentTokenizationRequest.md       
    - title: PaymentCardPaymentTokenizationRequest
      link: docs/schemas-md/PaymentCardPaymentTokenizationRequest.md       
    - title: PaymentDevicePaymentTokenizationRequest
      link: docs/schemas-md/PaymentDevicePaymentTokenizationRequest.md       
        
                          