name: Studio Validator
on:
  # Triggers the workflow on push or pull request events for the dev, stage, main, preview, and previous branch.
  push:
<<<<<<< HEAD
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]   
=======
    branches: [ develop,stage,main,preview,previous ]
  pull_request:
    branches: [ develop,stage,main,preview,previous ]
>>>>>>> preview

jobs:
  validator:
    uses: Fiserv/remote-actions/.github/workflows/validator-service.yaml@main
<<<<<<< HEAD
    secrets: inherit
=======
    secrets: inherit
>>>>>>> preview
